openapi: 3.0.0

info:
  title: Shelf APIs
  description: Shelf app documentation for APIs
  version: 1.0.0

servers:
  - url: http://localhost:8080/api
    description: Local server

paths:
  $ref: ./paths/index.yaml

components:
  $ref: ./components/index.yaml

security:
  - bearerAuth: []